//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisans_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum_Tur_Lisans
    {
        public int BolumTurID { get; set; }
        public string BolumTurAdi { get; set; }
    }
}
