//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisans_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolumler_Lisans_Uni
    {
        public int BolumID { get; set; }
        public string BolumAdi { get; set; }
        public int UniId { get; set; }
    
        public virtual Universiteler_Lisans Universiteler_Lisans { get; set; }
    }
}
