//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisans_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lisan
    {
        public int SonucID { get; set; }
        public Nullable<int> ProgramKodu { get; set; }
        public string Sehir { get; set; }
        public string Statu { get; set; }
        public string UniversiteAdi { get; set; }
        public string FakulteAdi { get; set; }
        public string BolumAdi { get; set; }
        public string BolumDetay { get; set; }
        public string PuanTuru { get; set; }
        public string OgrenimDili { get; set; }
        public string OgrenimTuru { get; set; }
        public string Burs { get; set; }
        public Nullable<int> B_Sira_2020 { get; set; }
        public string B_Sira_2019 { get; set; }
        public string B_Sira_2018 { get; set; }
        public string Kontenjan { get; set; }
        public string Kon_2021 { get; set; }
        public string Kont_2020 { get; set; }
        public string KonDegisimi { get; set; }
        public string OzelKosulveAciklamalar { get; set; }
        public Nullable<int> ilid { get; set; }
        public Nullable<int> UniID { get; set; }
        public Nullable<int> BolumID { get; set; }
        public Nullable<int> DilId { get; set; }
        public Nullable<int> PTid { get; set; }
        public Nullable<int> BursID { get; set; }
        public Nullable<int> StatuID { get; set; }
        public Nullable<int> TurID { get; set; }
    }
}
