//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisans_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TYT_LisansEntities1 : DbContext
    {
        public TYT_LisansEntities1()
            : base("name=TYT_LisansEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolum_Tur_Lisans> Bolum_Tur_Lisans { get; set; }
        public virtual DbSet<Bolumler_Lisans_Uni> Bolumler_Lisans_Uni { get; set; }
        public virtual DbSet<iller> illers { get; set; }
        public virtual DbSet<Lisan> Lisans { get; set; }
        public virtual DbSet<Universiteler_Lisans> Universiteler_Lisans { get; set; }
        public virtual DbSet<TopluViewLisan> TopluViewLisans { get; set; }
    }
}
