//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisans_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universiteler_Lisans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Universiteler_Lisans()
        {
            this.Bolumler_Lisans_Uni = new HashSet<Bolumler_Lisans_Uni>();
        }
    
        public int UniID { get; set; }
        public string UniversiteAdi { get; set; }
        public Nullable<int> ilid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bolumler_Lisans_Uni> Bolumler_Lisans_Uni { get; set; }
        public virtual iller iller { get; set; }
    }
}
